[package]
name = "rust-lesson"
version = "0.1.0"
authors = ["naoyuki_miyata <n.miyata080825@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib_demo = {git = "https://github.com/miyatama/lib-demo"}