[package]
name = "usecase"
version = "0.1.0"
edition = "2021"

[dependencies]
util = {path = "../util"}
repository = {path = "../repository"}

[dev-dependencies]
tokio = {version = "1.41.1", features = ["full"]}
repository = {path = "../repository", features = ["mock"]}