[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
util = {path = "../util"}
clap = {version = "4.5.23", features = ["derive"] }
log = {version = "0.4.22", features = ["std", "serde"]}