[package]
name = "infra"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = {path = "../domain"}
interface-adapter = {path = "../interface-adapter"}

clap = {version = "4.5.21", features = ["derive"]}
rand = "0.8"
serde = {version = "1.0", features = ["derive"]}
serde_yaml = "0.8"