[package]
name = "util"
version = "0.1.0"
edition = "2021"

[dependencies]
log = {version = "0.4.22", features = ["std", "serde"]}
serde_json = "1.0.132"
serde = {version = "1.0.214", features = ["derive"]}