[package]
name = "learn_reqwest"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
reqwest = "0.11.14"
futures = "0.3.31"
tokio = {version = "1.25.0", features = ["full"] }
serde_json = "1.0.132"
serde = {version = "1.0.214", features = ["derive"]}
headers = "0.3.9"