[package]
name = "image_process"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
imageproc = "0.25.0"
ab_glyph = "0.2.23"
image = "0.25.5"
log = {version = "0.4.22", features = ["std", "serde"]}
anyhow = "1.0.96"
num-traits = "0.2.19"