[package]
name = "about_mockall"
version = "0.1.0"
edition = "2021"

[dependencies]
mockall = "0.13.1"
mockall_double = "0.3.1"
uuid = { version = "1.11.0", features = [ "v4", "fast-rng", "macro-diagnostics" ] }
indexmap = "2.7.0"
fake = "3.0.1"
