[package]
name = "repository"
version = "0.1.0"
edition = "2021"

[features]
mock = ["mockall"]

[dependencies]
mockall = {version = "0.13.1", optional = true}
mockall_double = "0.3.1"
fake = "3.0.1"
util = {path = "../util"}
domain = {path = "../domain"}
