[package]
name = "repository"
version = "0.1.0"
edition = "2021"

[features]
mock = ["mockall"]

[dependencies]
util = {path = "../util"}
domain = {path = "../domain"}
mockall = {version = "0.13.1", optional = true }