[package]
name = "async_await"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = {version = "0.3", features = ["compat"] }
hyper= { version = "1.2.0", features = ["full"] }
tokio = "1.36.0"