[package]
name = "rust_yaml"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_yml = "0.0.12"
yaml-rust2 = "0.9"
log = {version = "0.4.22", features = ["std", "serde"]}