[package]
name = "about_tracing"
version = "0.1.0"
edition = "2021"

[dependencies]
thread_local = "1.1.4"
tracing = "0.1.41"
tracing-core = "=0.1.33"
tracing-subscriber = { version = "0.3.19", default-features = false, features = ["smallvec", "fmt", "ansi", "std"] }