[package]
name = "todo_graphql_client"
version = "0.1.0"
edition = "2021"

[dependencies]
graphql_client = {version = "0.14.0", features = ["reqwest-blocking"] }
serde = {version = "1.0.214", features = ["derive"]}